server:
  port: 8089
spring:
  datasource:
#    url: jdbc:mysql://mysql:3306/heima?useSSL=false
    url: jdbc:mysql://192.168.233.34:3306/es_heima?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 10086
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.233.34
    port: 5672
    username: pyip
    password: 123321
    virtual-host: /
logging:
  level:
    com.pyip: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.pyip.hotel.pojo